services:
  - type: web
    name: communiconnect-api
    env: python
    plan: free
    buildCommand: pip install -r requirements_render.txt
    startCommand: cd backend && python manage.py migrate && python manage.py load_geographic_data && python manage.py collectstatic --noinput && gunicorn communiconnect.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: communiconnect.settings_render
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .render.com,communiconnect-api.onrender.com,*
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: communiconnect-db
          property: connectionString
      - key: RENDER
        value: true

databases:
  - name: communiconnect-db
    plan: free
    databaseName: communiconnect
    user: communiconnect_user 