services:
  - type: web
    name: communiconnect-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn communiconnect.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: communiconnect.settings
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .render.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: communiconnect-db
          property: connectionString

databases:
  - name: communiconnect-db
    plan: free
    databaseName: communiconnect
    user: communiconnect_user 