# Generated by Django 4.2.7 on 2025-07-17 11:32

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/%Y/%m/%d/', validators=[posts.models.validate_file_size], verbose_name='Fichier')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('live', 'Live')], default='image', max_length=10)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Durée (vidéo)')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier')),
                ('is_appropriate', models.BooleanField(default=True, verbose_name='Contenu approprié')),
                ('approval_status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('inappropriate', 'Inapproprié')], default='pending', max_length=20, verbose_name="Statut d'approbation")),
                ('moderation_score', models.FloatField(blank=True, null=True, verbose_name='Score de modération')),
                ('moderation_details', models.JSONField(blank=True, default=dict, verbose_name='Détails de modération')),
                ('is_live', models.BooleanField(default=False, verbose_name='En direct')),
                ('live_stream_key', models.CharField(blank=True, max_length=100, verbose_name='Clé de stream')),
                ('live_viewers_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de spectateurs')),
                ('live_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Début du live')),
                ('live_ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin du live')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='is_live_post',
            field=models.BooleanField(default=False, verbose_name='Publication live'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('info', 'Information'), ('event', 'Événement'), ('help', "Demande d'aide"), ('announcement', 'Annonce'), ('discussion', 'Discussion'), ('live', 'Live')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='live_stream',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_post', to='posts.media', verbose_name='Stream live'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_files',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.media', verbose_name='Fichiers médias'),
        ),
    ]
