# Generated by Django 4.2.7 on 2025-07-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postcomment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='cdn_public_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID public CDN'),
        ),
        migrations.AddField(
            model_name='media',
            name='cdn_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL CDN'),
        ),
        migrations.AddField(
            model_name='media',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hauteur'),
        ),
        migrations.AddField(
            model_name='media',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Largeur'),
        ),
    ]
