# Generated by Django 4.2.7 on 2025-07-19 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_media_cdn_public_id_media_cdn_url_media_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shares_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PostShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_type', models.CharField(choices=[('share', 'Partage'), ('repost', 'Repost')], default='share', max_length=10)),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire du partage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partage de post',
                'verbose_name_plural': 'Partages de posts',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'post', 'share_type')},
            },
        ),
    ]
