# Generated by Django 4.2.7 on 2025-07-19 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_post_shares_count_postshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('telegram', 'Telegram'), ('email', 'Email'), ('copy_link', 'Copier le lien')], max_length=20)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_shares', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partage externe',
                'verbose_name_plural': 'Partages externes',
                'ordering': ['-shared_at'],
                'unique_together': {('user', 'post', 'platform')},
            },
        ),
    ]
