# Generated by Django 4.2.7 on 2025-07-19 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_externalshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('total_external_shares', models.PositiveIntegerField(default=0)),
                ('viral_score', models.FloatField(default=0.0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('reach_multiplier', models.FloatField(default=1.0)),
                ('whatsapp_shares', models.PositiveIntegerField(default=0)),
                ('facebook_shares', models.PositiveIntegerField(default=0)),
                ('twitter_shares', models.PositiveIntegerField(default=0)),
                ('telegram_shares', models.PositiveIntegerField(default=0)),
                ('email_shares', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='posts.post')),
            ],
            options={
                'verbose_name': 'Analytics de post',
                'verbose_name_plural': 'Analytics de posts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
