# Generated by Django 4.2.7 on 2025-07-23 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_postanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('text', 'Texte'), ('emoji', 'Emoji'), ('reaction', 'Réaction')], default='text', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_messages', to=settings.AUTH_USER_MODEL)),
                ('live_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='posts.post')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='posts.livechatmessage')),
            ],
            options={
                'verbose_name': 'Message de chat live',
                'verbose_name_plural': 'Messages de chat live',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['live_post', 'timestamp'], name='posts_livec_live_po_45fd34_idx'), models.Index(fields=['author', 'timestamp'], name='posts_livec_author__15087b_idx')],
            },
        ),
    ]
