# Generated by Django 4.2.7 on 2025-07-23 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_livechatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_live_recording',
            field=models.BooleanField(default=False, verbose_name='Enregistrement de live'),
        ),
        migrations.AddField(
            model_name='media',
            name='live_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recorded_videos', to='posts.post', verbose_name='Post live associé'),
        ),
        migrations.AlterField(
            model_name='post',
            name='live_stream',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_stream_post', to='posts.media', verbose_name='Stream live'),
        ),
    ]
