# Generated by Django 4.2.7 on 2025-07-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_media_is_live_recording_media_live_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalshare',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message personnalisé'),
        ),
        migrations.AddField(
            model_name='externalshare',
            name='share_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de partage'),
        ),
    ]
