# Generated by Django 4.2.7 on 2025-07-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_externalshare_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='externalshare',
            unique_together=set(),
        ),
    ]
